version: 2
general:
  artifacts:
    - dist/jest
jobs:
  build:
    docker:
      - image: 'circleci/node:9.7'
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - 'v1-dependencies-{{ checksum "package.json" }}'
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: 'v1-dependencies-{{ checksum "package.json" }}'
      - run: 'yarn test:cover'
